export const POLITICAL_COLORS = {
  left: '#FF4444',
  right: '#4444FF',
  center: '#9B59B6',
};

export const POLITICAL_LABELS = {
  left: "C'est de gauche",
  right: "C'est de droite",
  center: "C'est du centre",
};

export const POLITICAL_EMOJIS = {
  left: '✊🌱',
  right: '🦅💼',
  center: '⚖️',
};

// Question IDs with their point values (text comes from i18n)
// All questions are pooled here so the game shuffles across the full set.
export const POLITICAL_QUESTION_CONFIG = [
  { id: 'pol_1', points: { left: 3, right: 0 } },
  { id: 'pol_2', points: { left: 0, right: 2 } },
  { id: 'pol_3', points: { left: 2, right: 1 } },
  { id: 'pol_4', points: { left: 3, right: 2 } },
  { id: 'pol_5', points: { left: 3, right: 1 } },
  { id: 'pol_6', points: { left: 1, right: 1 } },
  { id: 'pol_7', points: { left: 2, right: 2 } },
  { id: 'pol_8', points: { left: 0, right: 3 } },
  { id: 'pol_9', points: { left: 2, right: 0 } },
  { id: 'pol_10', points: { left: 1, right: 2 } },
  { id: 'pol_11', points: { left: 2, right: 3 } },
  { id: 'pol_12', points: { left: 1, right: 3 } },
  { id: 'pol_13', points: { left: 3, right: 0 } },
  { id: 'pol_14', points: { left: 0, right: 2 } },
  { id: 'pol_15', points: { left: 2, right: 1 } },
  { id: 'pol_16', points: { left: 3, right: 2 } },
  { id: 'pol_17', points: { left: 3, right: 1 } },
  { id: 'pol_18', points: { left: 1, right: 1 } },
  { id: 'pol_19', points: { left: 2, right: 2 } },
  { id: 'pol_20', points: { left: 0, right: 3 } },
  { id: 'pol_21', points: { left: 2, right: 0 } },
  { id: 'pol_22', points: { left: 1, right: 2 } },
  { id: 'pol_23', points: { left: 2, right: 3 } },
  { id: 'pol_24', points: { left: 1, right: 3 } },
  { id: 'pol_25', points: { left: 3, right: 0 } },
  { id: 'pol_26', points: { left: 0, right: 2 } },
  { id: 'pol_27', points: { left: 2, right: 1 } },
  { id: 'pol_28', points: { left: 3, right: 2 } },
  { id: 'pol_29', points: { left: 3, right: 1 } },
  { id: 'pol_30', points: { left: 1, right: 1 } },
  { id: 'pol_31', points: { left: 2, right: 2 } },
  { id: 'pol_32', points: { left: 0, right: 3 } },
  { id: 'pol_33', points: { left: 2, right: 0 } },
  { id: 'pol_34', points: { left: 1, right: 2 } },
  { id: 'pol_35', points: { left: 2, right: 3 } },
  { id: 'pol_36', points: { left: 1, right: 3 } },
  { id: 'pol_37', points: { left: 3, right: 0 } },
  { id: 'pol_38', points: { left: 0, right: 2 } },
  { id: 'pol_39', points: { left: 2, right: 1 } },
  { id: 'pol_40', points: { left: 3, right: 2 } },
  { id: 'pol_41', points: { left: 3, right: 1 } },
  { id: 'pol_42', points: { left: 1, right: 1 } },
  { id: 'pol_43', points: { left: 2, right: 2 } },
  { id: 'pol_44', points: { left: 0, right: 3 } },
  { id: 'pol_45', points: { left: 2, right: 0 } },
  { id: 'pol_46', points: { left: 1, right: 2 } },
  { id: 'pol_47', points: { left: 2, right: 3 } },
  { id: 'pol_48', points: { left: 1, right: 3 } },
  { id: 'pol_49', points: { left: 3, right: 0 } },
  { id: 'pol_50', points: { left: 0, right: 2 } },
  { id: 'pol_51', points: { left: 2, right: 1 } },
  { id: 'pol_52', points: { left: 3, right: 2 } },
  { id: 'pol_53', points: { left: 3, right: 1 } },
  { id: 'pol_54', points: { left: 1, right: 1 } },
  { id: 'pol_55', points: { left: 2, right: 2 } },
  { id: 'pol_56', points: { left: 0, right: 3 } },
  { id: 'pol_57', points: { left: 2, right: 0 } },
  { id: 'pol_58', points: { left: 1, right: 2 } },
  { id: 'pol_59', points: { left: 2, right: 3 } },
  { id: 'pol_60', points: { left: 1, right: 3 } },
  { id: 'pol_61', points: { left: 3, right: 0 } },
  { id: 'pol_62', points: { left: 0, right: 2 } },
  { id: 'pol_63', points: { left: 2, right: 1 } },
  { id: 'pol_64', points: { left: 3, right: 2 } },
  { id: 'pol_65', points: { left: 3, right: 1 } },
  { id: 'pol_66', points: { left: 1, right: 1 } },
  { id: 'pol_67', points: { left: 2, right: 2 } },
  { id: 'pol_68', points: { left: 0, right: 3 } },
  { id: 'pol_69', points: { left: 2, right: 0 } },
  { id: 'pol_70', points: { left: 1, right: 2 } },
  { id: 'pol_71', points: { left: 2, right: 3 } },
  { id: 'pol_72', points: { left: 1, right: 3 } },
  { id: 'pol_73', points: { left: 3, right: 0 } },
  { id: 'pol_74', points: { left: 0, right: 2 } },
  { id: 'pol_75', points: { left: 2, right: 1 } },
  { id: 'pol_76', points: { left: 3, right: 2 } },
  { id: 'pol_77', points: { left: 3, right: 1 } },
  { id: 'pol_78', points: { left: 1, right: 1 } },
  { id: 'pol_79', points: { left: 2, right: 2 } },
  { id: 'pol_80', points: { left: 0, right: 3 } },
  { id: 'pol_81', points: { left: 2, right: 0 } },
  { id: 'pol_82', points: { left: 1, right: 2 } },
  { id: 'pol_83', points: { left: 2, right: 3 } },
  { id: 'pol_84', points: { left: 1, right: 3 } },
  { id: 'pol_85', points: { left: 3, right: 0 } },
  { id: 'pol_86', points: { left: 0, right: 2 } },
  { id: 'pol_87', points: { left: 2, right: 1 } },
  { id: 'pol_88', points: { left: 3, right: 2 } },
  { id: 'pol_89', points: { left: 3, right: 1 } },
  { id: 'pol_90', points: { left: 1, right: 1 } },
  { id: 'pol_91', points: { left: 2, right: 2 } },
  { id: 'pol_92', points: { left: 0, right: 3 } },
  { id: 'pol_93', points: { left: 2, right: 0 } },
  { id: 'pol_94', points: { left: 1, right: 2 } },
  { id: 'pol_95', points: { left: 2, right: 3 } },
  { id: 'pol_96', points: { left: 1, right: 3 } },
  { id: 'pol_97', points: { left: 3, right: 0 } },
  { id: 'pol_98', points: { left: 0, right: 2 } },
  { id: 'pol_99', points: { left: 2, right: 1 } },
  { id: 'pol_100', points: { left: 3, right: 2 } },
  { id: 'pol_101', points: { left: 3, right: 1 } },
  { id: 'pol_102', points: { left: 1, right: 1 } },
  { id: 'pol_103', points: { left: 2, right: 2 } },
  { id: 'pol_104', points: { left: 0, right: 3 } },
  { id: 'pol_105', points: { left: 2, right: 0 } },
  { id: 'pol_106', points: { left: 1, right: 2 } },
  { id: 'pol_107', points: { left: 2, right: 3 } },
  { id: 'pol_108', points: { left: 1, right: 3 } },
  { id: 'pol_109', points: { left: 3, right: 0 } },
  { id: 'pol_110', points: { left: 0, right: 2 } },
  { id: 'pol_111', points: { left: 2, right: 1 } },
  { id: 'pol_112', points: { left: 3, right: 2 } },
  { id: 'pol_113', points: { left: 3, right: 1 } },
  { id: 'pol_114', points: { left: 1, right: 1 } },
  { id: 'pol_115', points: { left: 2, right: 2 } },
  { id: 'pol_116', points: { left: 0, right: 3 } },
  { id: 'pol_117', points: { left: 2, right: 0 } },
  { id: 'pol_118', points: { left: 1, right: 2 } },
  { id: 'pol_119', points: { left: 2, right: 3 } },
  { id: 'pol_120', points: { left: 1, right: 3 } },
  { id: 'pol_121', points: { left: 3, right: 0 } },
  { id: 'pol_122', points: { left: 0, right: 2 } },
  { id: 'pol_123', points: { left: 2, right: 1 } },
  { id: 'pol_124', points: { left: 3, right: 2 } },
  { id: 'pol_125', points: { left: 3, right: 1 } },
  { id: 'pol_126', points: { left: 1, right: 1 } },
  { id: 'pol_127', points: { left: 2, right: 2 } },
  { id: 'pol_128', points: { left: 0, right: 3 } },
  { id: 'pol_129', points: { left: 2, right: 0 } },
  { id: 'pol_130', points: { left: 1, right: 2 } },
  { id: 'pol_131', points: { left: 2, right: 3 } },
  { id: 'pol_132', points: { left: 1, right: 3 } },
  { id: 'pol_133', points: { left: 3, right: 0 } },
  { id: 'pol_134', points: { left: 0, right: 2 } },
  { id: 'pol_135', points: { left: 2, right: 1 } },
  { id: 'pol_136', points: { left: 3, right: 2 } },
  { id: 'pol_137', points: { left: 3, right: 1 } },
  { id: 'pol_138', points: { left: 1, right: 1 } },
  { id: 'pol_139', points: { left: 2, right: 2 } },
  { id: 'pol_140', points: { left: 0, right: 3 } },
  { id: 'pol_141', points: { left: 2, right: 0 } },
  { id: 'pol_142', points: { left: 1, right: 2 } },
  { id: 'pol_143', points: { left: 2, right: 3 } },
  { id: 'pol_144', points: { left: 1, right: 3 } },
  { id: 'pol_145', points: { left: 3, right: 0 } },
  { id: 'pol_146', points: { left: 0, right: 2 } },
  { id: 'pol_147', points: { left: 2, right: 1 } },
  { id: 'pol_148', points: { left: 3, right: 2 } },
  { id: 'pol_149', points: { left: 3, right: 1 } },
  { id: 'pol_150', points: { left: 1, right: 1 } },
];
